name: Cypress Tests in Docker (latest)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress:
    runs-on: ubuntu-latest
    container:
      image: cypress/included:latest
      options: --user 1001

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run Cypress tests
        run: |
          cypress run --browser firefox --config integrationFolder=cypress/e2e

      - name: Upload Cypress screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload Cypress videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos